# Generated by Django 5.2 on 2025-05-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
